### ISSUE TITLE
open-graph for statemine

### ISSUE THREAD

**Issue by roiLeo** [kodadot/workers#104]
https://github.com/kodadot/nft-gallery/issues/6252#issuecomment-1594576607

**Comment by roiLeo** [comment]
<img width="928" alt="Capture d’écran 2023-06-22 à 10 37 17 AM" src="https://github.com/kodadot/workers/assets/9987732/ee5c81c0-6722-4c9b-bfe0-770db1e56635">

<img width="928" alt="Capture d’écran 2023-06-22 à 10 42 17 AM" src="https://github.com/kodadot/workers/assets/9987732/684c488d-93ed-4d0c-865f-cec10cd635c1">

❓

**Comment by preschian** [comment]
need to publish and update our package first, and then add `stmn` in `index.tsx`
![image](https://github.com/kodadot/workers/assets/734428/2427c359-4a66-4fe7-bb3e-a3b3ef9aecc5)

btw, with the current implementation of ssr-opengraph worker, our opengraph on nuxtjs app is not reflected on the prerendering case. because in this worker, it will rendering custom opengraph instead https://github.com/kodadot/workers/blob/7fe548b40a7fc0e17fad80ed8bbcd607dd16f3b1/ssr-opengraph/src/template.tsx#L11-L38

pros: cost efficiency
cons: need to maintain two different places for opengraph

with prerender.io, no need to maintain a different place for opengraph. https://github.com/kodadot/nft-gallery/issues/6284#issuecomment-1600743300

pros: simple
cons: comes at a price (but they have free tier). opengraph data not real-time (not sure we need real-time og or not)

**Comment by roiLeo** [comment]
For https://kodadot.xyz/stmn/gallery/19-2

<img width="908" alt="Capture d’écran 2023-06-22 à 12 16 12 PM" src="https://github.com/kodadot/workers/assets/9987732/1c492193-c401-4307-ba4a-b0889788faed">

**Comment by vikiival** [comment]
@preschian [the package was already published](https://www.npmjs.com/package/@kodadot1/static?activeTab=code)

**Comment by roiLeo** [comment]
Works on https://beta.kodadot.xyz/stmn/gallery/19-2

But still 500 on https://kodadot.xyz/stmn/gallery/19-2 even after deploy new stuff, maybe something is in cache on cloudflare?

**Comment by preschian** [comment]
probably cache. but, it works if I check it

![image](https://github.com/kodadot/workers/assets/734428/cba9d1cb-d77b-4fce-82fc-a2c835018ef2)

**Comment by roiLeo** [comment]
> probably cache. but, it works if I check it

Yup now it works, case closed

**Comment by preschian** [comment]
> So let's go with prerender.io if so. We will use them only for basic pages at least and maybe collections which are not so many of them.

I will prepare `cf-workers + prerender.io`
then compare `cf-workers + (prerender.io / manual construct)` and put them in separate routes and see the results

for example:
`/ksm/gallery/*` -> will hit `cf-workers + manual construct`
`/stmn/gallery/*` -> will hit `cf-workers + prerender.io`

wdyt?
