### ISSUE TITLE
Flex prerender on kodadot.xyz

### ISSUE THREAD

**Issue by yangwao** [kodadot/workers#111]
https://www.checkbot.io/guide/seo/?utm_source=checkbot-extension&utm_medium=extension&utm_content=learn-more#rule-set-mobile-scaling

![image](https://github.com/kodadot/nft-gallery/assets/5887929/58a56488-51d6-4328-a691-f18982535017)

**Comment by yangwao** [comment]
Something is still fundamentally bad with our prerender. 

Only `developers.` seems to work well, which has plain VitePress. 
- https://github.com/kodadot/docs/issues/95

Even Hello is somehow crappy (gitbook boo)

At kodadot.xyz 
---
only 9 URLs 🤔 from which are most of js bundles
![image](https://github.com/kodadot/nft-gallery/assets/5887929/a3e84ed8-2ff0-43e3-a578-ccead4fcb1c0)


Testing https://canary-netlify.kodadot.xyz
---

which is supposed to have Netlify prerender...

![image](https://github.com/kodadot/nft-gallery/assets/5887929/da37702f-65d3-4d1d-bb09-dc02068dfde6)

![image](https://github.com/kodadot/nft-gallery/assets/5887929/08f4e4e7-cb6d-4aa8-aa0f-060453cea3cb)

**Comment by yangwao** [comment]
cc @preschian seems Opengraph was closed, yet seems doesn't work that well.
- https://github.com/kodadot/workers/issues/88

Let's have look, where might be issue? Just notice that I even looked on Netlify and it's seems doesn't work either idk why

**Comment by vikiival** [comment]
Disallow _nuxt/* in robots.txt?

**Comment by yangwao** [comment]
> Disallow _nuxt/* in robots.txt?

Well, crawlbot should get HTML fragment in the first place 😅

**Comment by yangwao** [comment]
This might be related?
- https://github.com/kodadot/nft-gallery/issues/6312

**Comment by vikiival** [comment]
Fixed in #112 ?

**Comment by preschian** [comment]
which routes should we use through prerender? without prerender og tags won't work like this. no title or description on Google search results

![image](https://github.com/kodadot/workers/assets/734428/78371ccd-6460-417f-a016-d6d68a760ecf)

**Comment by preschian** [comment]
just want to make sure, why do we disallow `collection/items` on newer robots.txt anyway? we already index that on Google

![image](https://github.com/kodadot/workers/assets/734428/8b0a6e7a-775b-4467-8ae5-589243607748)

**Comment by vikiival** [comment]
Cc @yangwao 👀

**Comment by yangwao** [comment]
Re robots
We've been penalized for having a lot of items pages which we should put down for now so intent was decrease lot of those which google indexes but doesn't show for "reason", we going from something 2.75k and now at 1666 so let's see, positive trade off was that some seo pages starting working, which is great. Simple say, to have lot of pages we need some strong backlink traffic going which isn't case currently, but will be in the future

Collections we could put up as well tho gradually back.

We will be focusing on a few pages which by hello insights make a lot of views already should be on main kodadot to drive more seo traffic through

I'll make issues once we circle which pages should be put back to main for indexing

**Comment by preschian** [comment]
> We've been penalized

interesting, penalized from what actually? because this is quite difference with my experience

I just wanted to share my experience when I was still at an ecommerce company. What we did back then was index as many product pages as possible. Even though the Page Speed Insights score for those pages were still in the "poor" or "needs improvements" category. Being indexed by Google was still better than not being indexed at all. After that, we created several sitemaps. For example, a sitemap for popular products. The point is to create a sitemap for important pages

Roughly, it's similar to what Magic Eden did https://magiceden.io/robots.txt. In that link there is a special sitemap for popular collections. That sitemap is the one submitted to Google Search Console

I think we can follow what MagicEden has done. Create additional sitemaps for important collection/items pages, then submit these sitemaps to Google Search Console

Then, make sure the links in those sitemaps use prerendering. At least use the minimal prerendering that we already have. Or even better, use prerender.io. Because OpenGraph is not only used for social media sharing but also useful for SEO

| without prerendering. keyword: "kodadot carbonless" | with prerendering. keyword: "kusama canary fractal" |
|--------|--------|
| ![Screenshot 2023-06-30 162200](https://github.com/kodadot/workers/assets/734428/a1fb896e-ec37-4418-b635-419dffcb0fd3) | ![Screenshot 2023-06-30 162206](https://github.com/kodadot/workers/assets/734428/a47f064d-7b62-4cb3-aa0c-cb253455ab84) | 
| ![Screenshot 2023-06-30 162016](https://github.com/kodadot/workers/assets/734428/fa68a083-c67f-4d16-827c-72dae207f77b) | ![Screenshot 2023-06-30 162026](https://github.com/kodadot/workers/assets/734428/9ff29dd6-d781-45c7-a89e-e91ad96865f7) |
| no title. no description. blank page | at least there is a title and description with minimal page |
