### ISSUE TITLE
Image worker is super slow

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#39]
I have minted `bafkreibgt4iabra77rmw33i3czyj7nr6xh7ibnu5mf5zp4bvxhnzbbycha`

Tried different providers

```
https://bafkreibgt4iabra77rmw33i3czyj7nr6xh7ibnu5mf5zp4bvxhnzbbycha.ipfs.nftstorage.link/
```

```
https://ipfs.io/ipfs/bafkreibgt4iabra77rmw33i3czyj7nr6xh7ibnu5mf5zp4bvxhnzbbycha
```

On our gateway it fails

<img width="1792" alt="Screenshot 2023-03-08 at 16 33 36" src="https://user-images.githubusercontent.com/22471030/223757702-13e18444-68e6-4455-80a0-e8f4ff5db381.png">

**Comment by vikiival** [comment]
> if nftstorage provide dedicated gateway, we can use that also


Yes, it is a public one, feel free to use it within `Promise.any`
Just after few requests it will throw `429`

<img src="https://http.cat/429" />


> what if we are pinning images to our dedicated one also

sure

**Comment by vikiival** [comment]
https://community.cloudflare.com/t/community-tip-fixing-error-524-a-timeout-occurred/42342


```
FetchError: 524 Server Error (https://image.w.kodadot.xyz/ipfs/bafybeiaezqonb3mtegceu2hlngmsqsner6ztya3klctg3sv34olgckxtsa/00000191.json)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.any (index 0)
    at async fetchMetadata (/squid/lib/mappings/utils/metadata.js:17:16)
    at async handleMetadata (/squid/lib/mappings/shared/metadata.js:18:22)
    at async addResource (/squid/lib/mappings/v2/addResource.js:50:30)
    at async mainFrame (/squid/lib/mappings/v2/index.js:80:17)
    at async versionRouter (/squid/lib/mappings/index.js:26:9)
    at async Object.handleRemark [as handler] (/squid/lib/mappings/index.js:16:9)
    at async HandlerRunner.processBlock (/squid/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:579:29) 
```

**Comment by yangwao** [comment]
If i see here https://github.com/kodadot/workers/issues/33#issue-1584671855 

![image](https://user-images.githubusercontent.com/5887929/227217894-2d084df5-d1a7-4d04-8534-245619cee850.png)

mint push image to direct upload which put's it to R2/CFI should be immediately available?

**Comment by preschian** [comment]
closing this. lets continue here https://github.com/kodadot/workers/issues/132

> On our gateway it fails

just want to clarify, this is not our gateway, this is cloudflare-ipfs gateway

> mint pushes picture to direct upload which put's it to R2/CFI should be immediately available for image worker?

yes, it can be immediately available in `image-worker` if from `direct-upload` store to R2/CFI with the same format. CFI format in `image-workers` uses `https://imagedelivery.net/${imageId}/${cid}/public`. so, make sure to store that in the same format

currently, the `direct-upload worker` is still not using `Custom ID` when uploading to CFI. cmiiw 

so, even `direct-upload` stores it to CFI, `image-worker` is still not able to serve it immediately because of a different format. CFI in `image-workers`, `Custom ID === CID`
